### PR TITLE
Bug 469: Search Index sync crashes

### LINKED ISSUE #469: Bug:  Search Index sync crashes
**Beschreibung**
Es wurde eine grosse Menge Assets hinzugefügt auf dem INT System.
Der Search Index Sync crasht nun:

```
[0m 2025-03-25T14:22:58.654Z [0m  [44m DEBUG [49m  AssetSearchService  [34mAssets synced[39m  [total: [34m44117[39m, offset: [34m36000[39m]
[0m 2025-03-25T14:23:27.450Z [0m  [44m DEBUG [49m  AssetSearchService  [34mAssets synced[39m  [total: [34m44117[39m, offset: [34m37000[39m]
/app/node_modules/.prisma/client/runtime/library.js:121
`)}var Eo=({clientMethod:e,activeProvider:t})=>r=>{let n="",i;if(va(r))n=r.sql,i={values:Vt(r.values),__prismaRawParameters__:!0};else if(Array.isArray(r)){let[o,...s]=r;n=o,i={values:Vt(s||[]),__prismaRawParameters__:!0}}else switch(t){case"sqlite":case"mysql":{n=r.sql,i={values:Vt(r.values),__prismaRawParameters__:!0};break}case"cockroachdb":case"postgresql":case"postgres":{n=r.text,i={values:Vt(r.values),__prismaRawParameters__:!0};break}case"sqlserver":{n=Al(r),i={values:Vt(r.values),__prismaRawParameters__:!0};break}default:throw new Error(`The ${t} provider does not support ${e}`)}return i?.values?Nl(`prisma.${e}(${n}, ${i.values})`):Nl(`prisma.${e}(${n})`),{query:n,parameters:i}},Ll={requestArgsToMiddlewareArgs(e){return[e.strings,...e.values]},middlewareArgsToRequestArgs(e){let[t,...r]=e;return new ae(t,r)}},Fl={requestArgsToMiddlewareArgs(e){return[e]},middlewareArgsToRequestArgs(e){return e[0]}};function bo(e){return function(r,n){let i,o=(s=e)=>{try{return s===void 0||s?.kind==="itx"?i??=Ml(r(s)):Ml(r(s))}catch(a){return Promise.reject(a)}};return{get spec(){return n},then(s,a){return o().then(s,a)},catch(s){return o().catch(s)},finally(s){return o().finally(s)},requestTransaction(s){let a=o(s);return a.requestTransaction?a.requestTransaction(s):a},[Symbol.toStringTag]:"PrismaPromise"}}}function Ml(e){return typeof e.then=="function"?e:Promise.resolve(e)}var km={isEnabled(){return!1},getTraceParent(){return"00-10-10-00"},dispatchEngineSpans(){},getActiveContext(){},runInChildSpan(e,t){return t()}},wo=class{isEnabled(){return this.getGlobalTracingHelper().isEnabled()}getTraceParent(t){return this.getGlobalTracingHelper().getTraceParent(t)}dispatchEngineSpans(t){return this.getGlobalTracingHelper().dispatchEngineSpans(t)}getActiveContext(){return this.getGlobalTracingHelper().getActiveContext()}runInChildSpan(t,r){return this.getGlobalTracingHelper().runInChildSpan(t,r)}getGlobalTracingHelper(){return globalThis.PRISMA_INSTRUMENTATION?.helper??km}};function $l(){return new wo}function ql(e,t=()=>{}){let r,n=new Promise(i=>r=i);return{then(i){return--e===0&&r(t()),i?.(n)}}}function Vl(e){return typeof e=="string"?e:e.reduce((t,r)=>{let n=typeof r=="string"?r:r.level;return n==="query"?t:t&&(r==="info"||t==="info")?"info":n},void 0)}var $n=class{constructor(){this._middlewares=[]}use(t){this._middlewares.push(t)}get(t){return this._middlewares[t]}has(t){return!!this._middlewares[t]}length(){return this._middlewares.length}};var Bl=_(Ci());function qn(e){return typeof e.batchRequestIdx=="number"}function jl(e){if(e.action!=="findUnique"&&e.action!=="findUniqueOrThrow")return;let t=[];return e.modelName&&t.push(e.modelName),e.query.arguments&&t.push(xo(e.query.arguments)),t.push(xo(e.query.selection)),t.join("")}function xo(e){return`(${Object.keys(e).sort().map(r=>{let n=e[r];return typeof n=="object"&&n!==null?`(${r} ${xo(n)})`:r}).join(" ")})`}var _m={aggregate:!1,aggregateRaw:!1,createMany:!0,createManyAndReturn:!0,createOne:!0,deleteMany:!0,deleteOne:!0,executeRaw:!0,findFirst:!1,findFirstOrThrow:!1,findMany:!1,findRaw:!1,findUnique:!1,findUniqueOrThrow:!1,groupBy:!1,queryRaw:!1,runCommandRaw:!0,updateMany:!0,updateManyAndReturn:!0,updateOne:!0,upsertOne:!0};function Po(e){return _m[e]}var Vn=class{constructor(t){this.options=t;this.tickActive=!1;this.batches={}}request(t){let r=this.options.batchBy(t);return r?(this.batches[r]||(this.batches[r]=[],this.tickActive||(this.tickActive=!0,process.nextTick(()=>{this.dispatchBatches(),this.tickActive=!1}))),new Promise((n,i)=>{this.batches[r].push({request:t,resolve:n,reject:i})})):this.options.singleLoader(t)}dispatchBatches(){for(let t in this.batches){let r=this.batches[t];delete this.batches[t],r.length===1?this.options.singleLoader(r[0].request).then(n=>{n instanceof Error?r[0].reject(n):r[0].resolve(n)}).catch(n=>{r[0].reject(n)}):(r.sort((n,i)=>this.options.batchOrder(n.request,i.request)),this.options.batchLoader(r.map(n=>n.request)).then(n=>{if(n instanceof Error)for(let i=0;i<r.length;i++)r[i].reject(n);else for(let i=0;i<r.length;i++){let o=n[i];o instanceof Error?r[i].reject(o):r[i].resolve(o)}}).catch(n=>{for(let i=0;i<r.length;i++)r[i].reject(n)}))}}get[Symbol.toStringTag](){return"DataLoader"}};function ct(e,t){if(t===null)return t;switch(e){case"bigint":return BigInt(t);case"bytes":{let{buffer:r,byteOffset:n,byteLength:i}=Buffer.from(t,"base64");return new Uint8Array(r,n,i)}case"decimal":return new Pe(t);case"datetime":case"date":return new Date(t);case"time":return new Date(`1970-01-01T${t}Z`);case"bigint-array":return t.map(r=>ct("bigint",r));case"bytes-array":return t.map(r=>ct("bytes",r));case"decimal-array":return t.map(r=>ct("decimal",r));case"datetime-array":return t.map(r=>ct("datetime",r));case"date-array":return t.map(r=>ct("date",r));case"time-array":return t.map(r=>ct("time",r));default:return t}}function jn(e){let t=[],r=Dm(e);for(let n=0;n<e.rows.length;n++){let i=e.rows[n],o={...r};for(let s=0;s<i.length;s++)o[e.columns[s]]=ct(e.types[s],i[s]);t.push(o)}return t}function Dm(e){let t={};for(let r=0;r<e.columns.length;r++)t[e.columns[r]]=null;return t}var Nm=F("prisma:client:request_handler"),Bn=class{constructor(t,r){this.logEmitter=r,this.client=t,this.dataloader=new Vn({batchLoader:Ha(async({requests:n,customDataProxyFetch:i})=>{let{transaction:o,otelParentCtx:s}=n[0],a=n.map(p=>p.protocolQuery),l=this.client._tracingHelper.getTraceParent(s),u=n.some(p=>Po(p.protocolQuery.action));return(await this.client._engine.requestBatch(a,{traceparent:l,transaction:Lm(o),containsWrite:u,customDataProxyFetch:i})).map((p,d)=>{if(p instanceof Error)return p;try{return this.mapQueryEngineResult(n[d],p)}catch(f){return f}})}),singleLoader:async n=>{let i=n.transaction?.kind==="itx"?Ul(n.transaction):void 0,o=await this.client._engine.request(n.protocolQuery,{traceparent:this.client._tracingHelper.getTraceParent(),interactiveTransaction:i,isWrite:Po(n.protocolQuery.action),customDataProxyFetch:n.customDataProxyFetch});return this.mapQueryEngineResult(n,o)},batchBy:n=>n.transaction?.id?`transaction-${n.transaction.id}`:jl(n.protocolQuery),batchOrder(n,i){return n.transaction?.kind==="batch"&&i.transaction?.kind==="batch"?n.transaction.index-i.transaction.index:0}})}async request(t){try{return await this.dataloader.request(t)}catch(r){let{clientMethod:n,callsite:i,transaction:o,args:s,modelName:a}=t;this.handleAndLogRequestError({error:r,clientMethod:n,callsite:i,transaction:o,args:s,modelName:a,globalOmit:t.globalOmit})}}mapQueryEngineResult({dataPath:t,unpacker:r},n){let i=n?.data,o=this.unpack(i,t,r);return process.env.PRISMA_CLIENT_GET_TIME?{data:o}:o}handleAndLogRequestError(t){try{this.handleRequestError(t)}catch(r){throw this.logEmitter&&this.logEmitter.emit("error",{message:r.message,target:t.clientMethod,timestamp:new Date}),r}}handleRequestError({error:t,clientMethod:r,callsite:n,transaction:i,args:o,modelName:s,globalOmit:a}){if(Nm(t),Fm(t,i))throw t;if(t instanceof ee&&Mm(t)){let u=Ql(t.meta);xn({args:o,errors:[u],callsite:n,errorFormat:this.client._errorFormat,originalMethod:r,clientVersion:this.client._clientVersion,globalOmit:a})}let l=t.message;if(n&&(l=pn({callsite:n,originalMethod:r,isPanic:t.isPanic,showColors:this.client._errorFormat==="pretty",message:l})),l=this.sanitizeMessage(l),t.code){let u=s?{modelName:s,...t.meta}:t.meta;throw new ee(l,{code:t.code,clientVersion:this.client._clientVersion,meta:u,batchRequestIdx:t.batchRequestIdx})}else{if(t.isPanic)throw new ce(l,this.client._clientVersion);if(t instanceof B)throw new B(l,{clientVersion:this.client._clientVersion,batchRequestIdx:t.batchRequestIdx});if(t instanceof T)throw new T(l,this.client._clientVersion);if(t instanceof ce)throw new ce(l,this.client._clientVersion)}throw t.clientVersion=this.client._clientVersion,t}sanitizeMessage(t){return this.client._errorFormat&&this.client._errorFormat!=="pretty"?(0,Bl.default)(t):t}unpack(t,r,n){if(!t||(t.data&&(t=t.data),!t))return t;let i=Object.keys(t)[0],o=Object.values(t)[0],s=r.filter(u=>u!=="select"&&u!=="include"),a=Zi(o,s),l=i==="queryRaw"?jn(a):wt(a);return n?n(l):l}get[Symbol.toStringTag](){return"RequestHandler"}};function Lm(e){if(e){if(e.kind==="batch")return{kind:"batch",options:{isolationLevel:e.isolationLevel}};if(e.kind==="itx")return{kind:"itx",options:Ul(e)};Fe(e,"Unknown transaction kind")}}function Ul(e){return{id:e.id,payload:e.payload}}function Fm(e,t){return qn(e)&&t?.kind==="batch"&&e.batchRequestIdx!==t.index}function Mm(e){return e.code==="P2009"||e.code==="P2012"}function Ql(e){if(e.kind==="Union")return{kind:"Union",errors:e.errors.map(Ql)};if(Array.isArray(e.selectionPath)){let[,...t]=e.selectionPath;return{...e,selectionPath:t}}return e}var Gl="6.3.1";var Jl=Gl;var zl=_(Fi());var N=class extends Error{constructor(t){super(t+`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

PrismaClientKnownRequestError: 
Invalid `prisma.$queryRaw()` invocation:


Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)
    at Bn.handleRequestError (/app/node_modules/.prisma/client/runtime/library.js:121:7362)
    at Bn.handleAndLogRequestError (/app/node_modules/.prisma/client/runtime/library.js:121:6686)
    at Bn.request (/app/node_modules/.prisma/client/runtime/library.js:121:6393)
    at async l (/app/node_modules/.prisma/client/runtime/library.js:130:9645)
    at async StudyRepo.query (/app/main.js:26:65)
    at async StudyRepo.find (/app/main.js:10:2665)
    at async AssetSearchService.mapAssetToElastic (/app/main.js:1:58377)
    at async Promise.all (index 916)
    at async AssetSearchService.registerWithOptions (/app/main.js:1:51555)
    at async AssetSearchService.syncWithDatabase (/app/main.js:1:50770) {
  code: 'P2024',
  clientVersion: '6.3.1',
  meta: { connection_limit: 5, timeout: 10 }
}

Node.js v22.14.0
```

**Schritte zum Reproduzieren**

1. Sync auf INT starten
2. Bis ~82% warten
3. Server crash, restart, frontend Error Nachricht ist 

![Image](https://github.com/user-attachments/assets/9aa2e648-ab86-42bd-a164-fff2facf2273)

**Erwartetes Verhalten**
Search Sync läuft problemlos durch.

### PR DESCRIPTION
**Pull request by daniel-va**
Resolves #469.

Rewrites the search index to remove bottleneck encountered when syncing total assets multiple factors larger than the current "normal" state.

Measures taken:
- During the sync, at most 10 concurrent database connections will be requested.
  This solves the issue that originally sparked #469.
- The sync eagerly loads all mappings from `Asset` to `Contact` and `Favorites`.
  This should significantly reduce the amount of db requests, at the cost of memory.
  
I tested the sync locally on a copy of the production database.
To ensure that it handles larger amounts of assets well, I artificially multiplied the amount of assets by 3, which was successfully processed. We currently do not have access to the set of assets that original problem on INT, but I don't expect any more problems with it after this PR.

### CODE REVIEW

File: apps/server-asset-sg/src/utils/process-queue.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+  }
+
+  /**
+   * Runs a task. Automatically continues to run any queued tasks afterward.
+   *
+   * @param process The task to run.
+   * @private
+   */
+  private async run(process: Process): Promise<void> {
+    const promise = (process.run() as Promise<void> | undefined) ?? Promise.resolve();
```
Comment (Tugark) [inline apps/server-asset-sg/src/utils/process-queue.ts:57]: Maybe use instanceof to not have to rely on type assertions and improve readability (for the sake of simplicity):

```
const run = process.run()
const promise = run instanceof Promise ? run : Promise.resolve();
```

Not sure about timing issues, but I don't think they'd matter in this context.

File: apps/server-asset-sg/src/utils/process-queue.ts [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+  /**
+   * Registers a new tasks to be run.
+   *
+   * @param run The task to run.
+   */
+  add(run: () => void | Promise<void>): Promise<void> {
+    if (this.active.size < this.quantity) {
+      return new Promise((resolve) => {
+        const process: Process = { run, resolve };
+        this.run(process).then();
```
Comment (Tugark) [inline apps/server-asset-sg/src/utils/process-queue.ts:25]: We do not handle rejections explicitly, so the process would remove itself and any exception would be logged to the error stream, right?

File: apps/server-asset-sg/src/features/assets/search/asset-search.service.ts [hunk 3]
```diff
@@ -66,8 +64,17 @@ export class AssetSearchService {
     private readonly studyRepo: StudyRepo
   ) {}
 
-  register(oneOrMore: AssetEditDetail | AssetEditDetail[]): Promise<void> {
-    return this.registerWithOptions(oneOrMore, { index: INDEX, shouldRefresh: true });
+  register(asset: AssetEditDetail): Promise<void> {
+    return this.writer().write(asset);
+  }
+
+  writer(options?: AssetSearchWriterOptions): AssetSearchWriter {
```
Comment (Tugark) [inline apps/server-asset-sg/src/features/assets/search/asset-search.service.ts:71]: Rename to what the method does, i.e. `getWriter` since it's not a property.

File: apps/server-asset-sg/src/features/assets/search/asset-search.writer.ts [hunk 4]
```diff
@@ -0,0 +1,202 @@
...
+    private readonly options: AssetSearchWriterOptions
+  ) {
+    this.eager = options.isEager ? this.fetchEager() : Promise.resolve(null);
+  }
+
+  async write(oneOrMore: AssetEditDetail | AssetEditDetail[]): Promise<void> {
+    const assets = Array.isArray(oneOrMore) ? oneOrMore : [oneOrMore];
+    const operations: Array<BulkOperationContainer | ElasticSearchAsset> = Array(assets.length * 2);
+
+    const processQueue = new ProcessQueue(10);
```
Comment (Tugark) [inline apps/server-asset-sg/src/features/assets/search/asset-search.writer.ts:32]: I'd move this to either a constant at the beggining of the file (i.e. `const QUEUE_SIZE = 10`) or add it as option. Right now it's a bit buried here.

**Review by Tugark — APPROVED** [review]
I wasn't able to properly check it locally because my dev env is somehow broken - but nice implementation 👍

**Review by Tugark — APPROVED** [review]
