### PR TITLE
Feature 192: Bug - Performance Suche

### LINKED ISSUE #192: Bug: Performance Suche
**Beschreibung**

Die Performance der Suche ist degradiert seit dem Refactor.

**Beobachtetes Verhalten**

Vergleiche Dauer einer Suche auf Dev und Prod:

1. Suche nach 'test'. 57 Ergebnisse.
    Dev: 900ms, 300ms (stats)
    Prod: 47ms 
2. Suche nach 'n1'. 846 Ergebnisse.
    Dev: 10240ms, 300ms (stats)
    Prod: 1140ms 

**Erwartetes Verhalten**
Die Performance ist verleichbar auf beiden Systemen.
Verschiedene Requests für die Filter und Suchergebnisse führen zu einem unstimmigen Bild um UI - ist das sinnvoll?

### PR DESCRIPTION
**Pull request by daniel-va**
Resolves #192.

- Replaces `/api/all-study` with `/api/studies`, which returns studies as concise CSV which is loaded, sent and parsed in chunks. The size of the transmitted data is about half as large as before.
- Moves all search aspects, including polygon search and data fetching, into Elasticsearch.

### CODE REVIEW

File: apps/server-asset-sg/src/features/studies/studies.controller.ts [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+          studies.length === 0 || studies.length < nextLimit
+            ? null
+            : studyRepo.list({ limit: BATCH_SIZE, offset: count });
+
+        // Update the `nextLimit`, as in the first iteration, it's set to INITIAL_BATCH_SIZE.
+        nextLimit = BATCH_SIZE;
+
+        // Write the current batch to the response.
+        for (const study of studies) {
+          yield `${study.id.substring(6)};${study.assetId};${+study.isPoint};${study.center.x};${study.center.y}\n`;
```
Comment (vej-ananas) [inline apps/server-asset-sg/src/features/studies/studies.controller.ts:64]: Maybe move the formatting to an external function + a test?

File: apps/server-asset-sg/src/features/studies/study.repo.ts [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+      SELECT
+        study_id as "id",
+        asset_id AS "assetId",
+        is_point AS "isPoint",
+        SUBSTRING(centroid_geom_text FROM 7 FOR length(centroid_geom_text) -7) AS "center"
+      FROM public.all_study
+      ${condition}
+    `;
+    return studies.map((study) => {
+      const center = LV95FromSpaceSeparatedString.decode(study.center);
```
Comment (vej-ananas) [inline apps/server-asset-sg/src/features/studies/study.repo.ts:57]: This basically validates the coordinate range, correct?

File: apps/server-asset-sg/src/features/studies/study.repo.ts [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+      return {
+        ...study,
+        center: (center as E.Right<LV95>).right,
```
Comment (vej-ananas) [inline apps/server-asset-sg/src/features/studies/study.repo.ts:60]: If we want to go full performance, we would not have to wrap the coordinates in an object just to put in in a csv

File: libs/asset-viewer/src/lib/services/asset-search.service.ts
Comment (vej-ananas) [inline libs/asset-viewer/src/lib/services/asset-search.service.ts:1]: Remove unused imports

File: libs/shared/src/lib/models/all-study.ts [hunk 4]
```diff
@@ -10,4 +10,10 @@ export const AllStudyDTOFromAPI = D.struct({
 });
 export type AllStudyDTOFromAPI = D.TypeOf<typeof AllStudyDTOFromAPI>;
 export const AllStudyDTOsFromAPI = D.array(AllStudyDTOFromAPI);
```
Comment (vej-ananas) [inline libs/shared/src/lib/models/all-study.ts:12]: Kann man diese löschen? Wann immer möglich und angebracht, unbenutzte Typen löschen

**Review by vej-ananas — CHANGES_REQUESTED** [review]

**Review by vej-ananas — APPROVED** [review]
