### PR TITLE
Fix bug that displayed the wrong language for users

### LINKED ISSUE #447: Bug:  Sprache in User Detailansicht inkonsistent
**Beschreibung**
Unter der Benutzerverwaltung Detailansicht wird die Sprache nicht immer korrekt wiedergegeben.

Gilt für INT und DEV
**Schritte zum Reproduzieren**

1. Gehe zur Seite `/admin/users`
2. Klicke auf einen User mit z.B. Sprache `de`
3. Klicke zurück
4. Klicke auf einen anderen Benutzer mit anderer Sprache, z.B. `it`
5. Das Dropdown zeigt die erste Sprache, z.B. `deutsch` anstatt `italienisch`

**Beobachtetes Verhalten**
Das Sprachdropdown ist mit vorigen Werten befüllt.

**Erwartetes Verhalten**
Es werden die tatsächlichen Daten des aktuellen Benutzers gezeigt.

### PR DESCRIPTION
**Pull request by TIL-EBP**
resolves #447

### CODE REVIEW

File: libs/admin/src/lib/components/admin-page/admin-page.component.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export class AdminPageComponent implements OnInit, OnDestroy {
   @ViewChild('templateDrawerPortalContent') templateDrawerPortalContent!: TemplateRef<unknown>;
 
   public workgroup?: Workgroup = undefined;
+  public user?: User = undefined;
```
Comment (Tugark) [inline libs/admin/src/lib/components/admin-page/admin-page.component.ts:22]: Not sure about coding conventions - but I'd remove the explicit `undefined` definition since it is implied by using `user?`.

File: libs/admin/src/lib/components/admin-page/admin-page.component.ts [hunk 2]
```diff
@@ -91,5 +92,11 @@ export class AdminPageComponent implements OnInit, OnDestroy {
         this.workgroup = workgroup ?? undefined;
       })
     );
+
+    this.subscriptions.add(
+      this.selectedUser$.subscribe((user) => {
+        this.user = user ?? undefined;
```
Comment (Tugark) [inline libs/admin/src/lib/components/admin-page/admin-page.component.ts:98]: Is there a reason that `selectSelectedUser` returns `null`?

I think you could simplify it if that one returned `undefined` instead of `null`; or then I'd question why `this.user` is `undefined` and needs this explicit mapping from `null` to `unfedined`

Comment (TIL-EBP) [reply libs/admin/src/lib/components/admin-page/admin-page.component.ts:98]: Fair point. I honestly do not know why we defined it that way, but in the state the user is defined as `User | null` (same for workgroups). I guess this could be changed to `User | undefined`, but I don't really feel like touching the state now for this bug. 
So i just changed the `this.user` to be `User | null` instead

**Review by Tugark — APPROVED** [review]
